#! /bin/bash

if [[ -z $1 ]]; then
    LOCAL_PATH=$(pwd)
else
    LOCAL_PATH="${1}"
fi

IP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' grafana-influxdb_con )

if [ xIP = x ] ; then
	echo " container grafana-influxdb_con is not running, please start container and do that again"
	exit 1
fi

docker run -v ${LOCAL_PATH}/src:/src -v ${LOCAL_PATH}/dst:/dst --env SRC_PATH=/src --env DST_PATH=/dst --env TASK=PUSH --env IP=$IP --name atop-pusher  atop-convert && \
docker rm atop-pusher

